server:
  port: 8972

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:6033/encore
#    url: jdbc:mariadb://database:3306/encore # 이렇게 하는건 방법이 아님
    username: todo_user
    password: todo_passwd

mybatis:
  mapper-locations: mappers/*.xml